name: WorldByPlayer
version: '${project.version}'
main: fr.kenda.worldbyplayer.WorldByPlayer
api-version: 1.19
commands:
  hub:
    description: return to main world
    aliases:
      - lobby
  world:
    description: Show nether and end world
    aliases:
      - nether
      - end
      - worldteleport
      - wl
  worldconfig:
    description: Command to config your own world
    aliases:
      - worldgenerator
      - modify
      - worldmodify
      - config
      - wconfig
  worldadmin:
    description: Command to administrate world
    aliases:
    - worlda
    - wadmin
  menu:
    description: Command to show menu in hub
    aliases:
      - navigation
  spawn:
    description: Go back to spawn of world